---
#- name: Update all packages to their latest version
#  ansible.builtin.apt:
#    name: "*"
#    state: latest

- name: Install Java package (Ubuntu/Debian)
  apt:
    name: "{{ java_apt_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Java package (CentOS/RHEL)
  yum:
    name: "{{ java_yum_package }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'RedHat'
