---
- name: install packages
  hosts: clients
  become: yes

  tasks:
  - name: update packages ubuntu
    ansible.builtin.apt: 
      update_cache: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: update packages centos
    ansible.builtin.yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"
