---
- name: latest Apache version installed
  ansible.builtin.apt:
    name: apache2
    state: latest
  notify: apache-restart

- name: firewalld enabled and running
  ansible.builtin.service:
    name: ufw
    enabled: true
    state: stopped

- name: Extract file
  ansible.builtin.unarchive:
    src: ./files/website.tar
    dest: /var/www/html
  notify:
      - Restart apache

