---
- name: install packages
  hosts: clients
  become: yes

  tasks:
  - name: get data from server
    ansible.builtin.shell: date
    register: output
 
  - debug: msg="the date from the server is {{output.stdout}} "
